<?php
// PRESENTATION LAYER
require_once 'products.php';
require_once 'functions.php';
$totalNilaiStok = hitungTotalNilaiStok($products);
$jumlahProduk = count($products);
$jumlahStokKritis = hitungJumlahStokKritis($products);
?>
<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FashionPoint | Sistem Informasi Produk</title>
<style>
:root{--primary:#9f1239;--bg:#faf7f8;--text:#292524;--muted:#78716c;--border:#eee4e7;--danger:#be123c;--success:#047857}*{box-sizing:border-box;margin:0;padding:0}body{font-family:Arial,sans-serif;background:var(--bg);color:var(--text)}.hero{background:linear-gradient(135deg,#4a0b20,#9f1239 60%,#be185d);color:#fff;padding:42px 6%}.hero-inner{max-width:1180px;margin:auto}.brand{display:flex;align-items:center;gap:12px;margin-bottom:28px}.brand-icon{width:45px;height:45px;display:grid;place-items:center;background:#ffffff24;border-radius:13px;font-size:22px}.brand strong{font-size:20px}.brand span{display:block;font-size:12px;opacity:.78}.hero h1{font-size:clamp(28px,4vw,42px);margin-bottom:10px}.hero p{color:#ffe4e6;max-width:700px;line-height:1.7}.content{width:88%;max-width:1180px;margin:-28px auto 40px;position:relative}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-bottom:22px}.stat{background:#fff;border:1px solid var(--border);border-radius:16px;padding:22px;box-shadow:0 8px 25px #2925240f}.stat-label{color:var(--muted);font-size:12px;font-weight:bold;margin-bottom:9px}.stat-value{font-size:25px;font-weight:800}.table-card{background:#fff;border:1px solid var(--border);border-radius:16px;overflow:hidden;box-shadow:0 8px 25px #2925240f}.table-header{padding:22px 24px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;gap:15px}.table-header h2{font-size:19px;margin-bottom:4px}.table-header p{color:var(--muted);font-size:13px}.legend{display:flex;gap:8px}.badge{display:inline-flex;padding:6px 10px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.safe{color:var(--success);background:#ecfdf5}.critical{color:var(--danger);background:#fff1f2}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:1000px}th{padding:13px 15px;background:#fdf8f9;color:#78716c;font-size:11px;text-align:left;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid var(--border)}td{padding:15px;border-bottom:1px solid var(--border);font-size:13px;vertical-align:middle}tbody tr:last-child td{border-bottom:none}tbody tr:hover{background:#fffafb}tbody tr.critical-row{background:#fff1f2}.product-id{color:var(--primary);font-weight:800}.product-name{font-weight:750}.category{color:#57534e}.description{color:var(--muted);max-width:260px}.price,.stock,.stock-value{white-space:nowrap;font-weight:650}.footer{text-align:center;color:var(--muted);font-size:12px;margin-top:18px}@media(max-width:760px){.hero{padding:30px 6% 52px}.content{width:92%}.stats{grid-template-columns:1fr}.table-header{align-items:flex-start;flex-direction:column}.legend{flex-wrap:wrap}}
</style></head>
<body>
<header class="hero"><div class="hero-inner"><div class="brand"><div class="brand-icon">👗</div><div><strong>FashionPoint</strong><span>Product Information System</span></div></div><h1>Sistem Informasi Persediaan Toko Pakaian</h1><p>Sistem sederhana untuk menyimpan, mengolah, dan menampilkan informasi produk pakaian serta memantau nilai persediaan dan stok kritis.</p></div></header>
<main class="content"><section class="stats"><div class="stat"><div class="stat-label">TOTAL PRODUK</div><div class="stat-value"><?= $jumlahProduk ?> Produk</div></div><div class="stat"><div class="stat-label">STOK KRITIS</div><div class="stat-value"><?= $jumlahStokKritis ?> Produk</div></div><div class="stat"><div class="stat-label">TOTAL NILAI STOK</div><div class="stat-value"><?= formatRupiah($totalNilaiStok) ?></div></div></section>
<section class="table-card"><div class="table-header"><div><h2>Daftar Produk Pakaian</h2><p>Informasi produk dan kondisi persediaan toko.</p></div><div class="legend"><span class="badge safe">● Stok Aman</span><span class="badge critical">● Stok Kritis</span></div></div><div class="table-wrap"><table><thead><tr><th>No</th><th>ID Produk</th><th>Nama Produk</th><th>Kategori</th><th>Harga</th><th>Stok</th><th>Nilai Stok</th><th>Status</th><th>Deskripsi</th></tr></thead><tbody>
<?php foreach ($products as $index => $product): $critical = isStokKritis($product['stok']); ?><tr class="<?= $critical ? 'critical-row' : '' ?>"><td><?= $index+1 ?></td><td class="product-id"><?= htmlspecialchars($product['id']) ?></td><td class="product-name"><?= htmlspecialchars($product['nama']) ?></td><td class="category"><?= htmlspecialchars($product['kategori']) ?></td><td class="price"><?= formatRupiah($product['harga']) ?></td><td class="stock"><?= $product['stok'] ?></td><td class="stock-value"><?= formatRupiah(hitungNilaiStok($product['harga'],$product['stok'])) ?></td><td><?php if($critical): ?><span class="badge critical">Stok Kritis</span><?php else: ?><span class="badge safe">Aman</span><?php endif; ?></td><td class="description"><?= htmlspecialchars($product['deskripsi']) ?></td></tr><?php endforeach; ?>
</tbody></table></div></section><div class="footer">FashionPoint © Mini Project 1 — Sistem Informasi Produk</div></main></body></html>
